# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S.M.A.Weerasinghe-COBSCComp192P-025' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S.M.A.Weerasinghe-COBSCComp192P-025

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  target 'S.M.A.Weerasinghe-COBSCComp192P-025Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'S.M.A.Weerasinghe-COBSCComp192P-025UITests' do
    # Pods for testing
  end

end
